[mypy]
# Global settings
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
exclude = env/

# Per-module settings to ignore missing imports for libraries without stubs
[mypy-reportlab.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-alembic.*]
ignore_missing_imports = True
