"""Add Product and Shipment models

Revision ID: d2522fdabd36
Revises: 71bcb5ba1383
Create Date: 2026-03-03 03:12:57.423662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2522fdabd36'
down_revision: Union[str, Sequence[str], None] = '71bcb5ba1383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_ref', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('origin_country', sa.String(length=2), nullable=False),
    sa.Column('is_food', sa.Boolean(), nullable=False),
    sa.Column('processing_state', sa.String(length=32), nullable=True),
    sa.Column('physical_form', sa.String(length=32), nullable=True),
    sa.Column('unit_weight_g', sa.Integer(), nullable=True),
    sa.Column('dimensions_mm', sa.JSON(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('packaging', sa.JSON(), nullable=True),
    sa.Column('animal_derived_flags', sa.JSON(), nullable=True),
    sa.Column('hs_base6', sa.String(length=16), nullable=True),
    sa.Column('active_classification_id', sa.Integer(), nullable=True),
    sa.Column('country_specific_codes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_classification_id'], ['hs_classifications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_ref', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('destination_country', sa.String(length=2), nullable=False),
    sa.Column('shipping_mode', sa.String(length=32), nullable=False),
    sa.Column('incoterm', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_weight_g', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_order_ref'), 'shipments', ['order_ref'], unique=False)
    op.create_index(op.f('ix_shipments_trace_id'), 'shipments', ['trace_id'], unique=False)
    op.create_table('document_exports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('storage_url', sa.String(length=512), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_exports_shipment_id'), 'document_exports', ['shipment_id'], unique=False)
    op.create_table('shipment_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_value', sa.Float(), nullable=False),
    sa.Column('line_weight_g', sa.Integer(), nullable=False),
    sa.Column('hs_base6', sa.String(length=16), nullable=True),
    sa.Column('country_specific_code', sa.String(length=32), nullable=True),
    sa.Column('origin_country', sa.String(length=2), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_lines_product_id'), 'shipment_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipment_lines_shipment_id'), 'shipment_lines', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_audit_events_ts'), 'audit_events', ['ts'], unique=False)
    op.alter_column('hs_classifications', 'product_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='product_id::integer')
    op.create_foreign_key(None, 'hs_classifications', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_webhook_dlq_expires_at'), 'webhook_dlq', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_dlq_expires_at'), table_name='webhook_dlq')
    op.drop_constraint(None, 'hs_classifications', type_='foreignkey')
    op.alter_column('hs_classifications', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_events_ts'), table_name='audit_events')
    op.drop_index(op.f('ix_shipment_lines_shipment_id'), table_name='shipment_lines')
    op.drop_index(op.f('ix_shipment_lines_product_id'), table_name='shipment_lines')
    op.drop_table('shipment_lines')
    op.drop_index(op.f('ix_document_exports_shipment_id'), table_name='document_exports')
    op.drop_table('document_exports')
    op.drop_index(op.f('ix_shipments_trace_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_ref'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('products')
    # ### end Alembic commands ###
